name: Builds, tests & co

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

permissions: read-all

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
      - name: Install system dependencies
        run: sudo apt install musl-dev 
      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "ocaml-option-static,ocaml-5.1.1,"
      - name: Install system dependencies
        run: sudo apt install musl-dev
      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build --profile static
